---
# Add your data here:
PV_EMAIL : ""               # e-mail address you used to register at M-TEC portal
PV_PASSWORD : ""            # password you used to register at M-TEC portal

# MQTT
MQTT_SERVER : "localhost"   # MQTT server 
MQTT_PORT : 1883            # MQTT server port
MQTT_LOGIN  : " "           # MQTT Login
MQTT_PASSWORD : ""          # MQTT Password  
MQTT_TOPIC : "MTEC"         # MQTT topic name (top-level)  

POLL_FREQUENCY : 60         # query data every N seconds
DEBUG : False               # Set to True to get verbose debug messages
WRITE_STATION_DATA : True   # Choose if you want to write station data to MQTT
WRITE_DEVICE_DATA : True    # Choose if you want to write device data to MQTT

MQTT_FLOAT_FORMAT : "{:.2f}"     # Defines how to format float values 

##########################
# Base config - probably no need to change
PV_BASE_URL : "https://energybutler.mtec-portal.com/api/sys/"  # Base URL of API
PV_TIMEOUT : 3         # Timeout (seconds) for querying the API
PV_MAX_LOGIN_RETRY : 3 # No. of retries for login

PV_DEMO_ACCOUNT : "2312942037@qq.com"    # e-mail adress of Demo account
PV_DEMO_STATION_ID : "1587705243920052226"

