---
# Add your data here:
PV_EMAIL : ""               # e-mail address you used to register at M-TEC portal
PV_PASSWORD : ""            # password you used to register at M-TEC portal
PV_STATION_ID : ""          # Your individual MCT power stationId

##########################
# Base config - probably no need to change
BASE_URL : "https://energybutler.mtec-portal.com/api/sys/"  # Base URL of API
TIMEOUT : 3         # Timeout (seconds) for querying the API
MAX_LOGIN_RETRY : 3 # No. of retries for login

DEMO_ACCOUNT : "2312942037@qq.com"    # e-mail adress of Demo account
DEMO_STATION_ID : "1587705243920052226"

